# Generated by Django 5.1.6 on 2025-02-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
