# Generated by Django 5.1.6 on 2025-03-22 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_favorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
    ]
